# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\PycharmProjects\gameLogic\gui\AttestationTile.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AttestationTile(object):
    def setupUi(self, AttestationTile):
        AttestationTile.setObjectName("AttestationTile")
        AttestationTile.resize(341, 263)
        AttestationTile.setStyleSheet("\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(AttestationTile)
        self.verticalLayout.setObjectName("verticalLayout")
        self.valueButton = QtWidgets.QPushButton(AttestationTile)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.valueButton.sizePolicy().hasHeightForWidth())
        self.valueButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.valueButton.setFont(font)
        self.valueButton.setStyleSheet("background-color: rgb(70, 255, 203);")
        self.valueButton.setObjectName("valueButton")
        self.verticalLayout.addWidget(self.valueButton)

        self.retranslateUi(AttestationTile)
        QtCore.QMetaObject.connectSlotsByName(AttestationTile)

    def retranslateUi(self, AttestationTile):
        _translate = QtCore.QCoreApplication.translate
        AttestationTile.setWindowTitle(_translate("AttestationTile", "Form"))
        self.valueButton.setText(_translate("AttestationTile", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AttestationTile = QtWidgets.QWidget()
    ui = Ui_AttestationTile()
    ui.setupUi(AttestationTile)
    AttestationTile.show()
    sys.exit(app.exec_())
