# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\PycharmProjects\gameLogic\gui\MainGameMenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainGameMenu(object):
    def setupUi(self, MainGameMenu):
        MainGameMenu.setObjectName("MainGameMenu")
        MainGameMenu.resize(709, 648)
        self.verticalLayout = QtWidgets.QVBoxLayout(MainGameMenu)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_3 = QtWidgets.QWidget(MainGameMenu)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget = QtWidgets.QWidget(self.widget_3)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(55)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_4.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.widget_3)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.playButton = QtWidgets.QPushButton(self.widget_2)
        self.playButton.setObjectName("playButton")
        self.verticalLayout_3.addWidget(self.playButton, 0, QtCore.Qt.AlignHCenter)
        self.settingsButton = QtWidgets.QPushButton(self.widget_2)
        self.settingsButton.setObjectName("settingsButton")
        self.verticalLayout_3.addWidget(self.settingsButton, 0, QtCore.Qt.AlignHCenter)
        self.rulesButton = QtWidgets.QPushButton(self.widget_2)
        self.rulesButton.setObjectName("rulesButton")
        self.verticalLayout_3.addWidget(self.rulesButton, 0, QtCore.Qt.AlignHCenter)
        self.statisticsButton = QtWidgets.QPushButton(self.widget_2)
        self.statisticsButton.setObjectName("statisticsButton")
        self.verticalLayout_3.addWidget(self.statisticsButton, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.exitButton = QtWidgets.QPushButton(self.widget_2)
        self.exitButton.setObjectName("exitButton")
        self.verticalLayout_3.addWidget(self.exitButton, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_4.addWidget(self.widget_2, 0, QtCore.Qt.AlignTop)
        self.verticalLayout.addWidget(self.widget_3)

        self.retranslateUi(MainGameMenu)
        QtCore.QMetaObject.connectSlotsByName(MainGameMenu)

    def retranslateUi(self, MainGameMenu):
        _translate = QtCore.QCoreApplication.translate
        MainGameMenu.setWindowTitle(_translate("MainGameMenu", "MainGameMenu"))
        self.label.setText(_translate("MainGameMenu", "БлитцСессия"))
        self.playButton.setText(_translate("MainGameMenu", "Игра"))
        self.settingsButton.setText(_translate("MainGameMenu", "Настройки"))
        self.rulesButton.setText(_translate("MainGameMenu", "Правила"))
        self.statisticsButton.setText(_translate("MainGameMenu", "Статистика"))
        self.exitButton.setText(_translate("MainGameMenu", "Выход"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainGameMenu = QtWidgets.QWidget()
    ui = Ui_MainGameMenu()
    ui.setupUi(MainGameMenu)
    MainGameMenu.show()
    sys.exit(app.exec_())
